### ISSUE TITLE
Picture scrolls keep jumping back up to the start

### ISSUE THREAD

**Issue by HowdHe** [roysix/infy-scroll#14]
As I'm scrolling down an infy scroll of pictures using the Increment > Media function, every time a new image in the series loads, it jumps the scroll right back up to the top, and I have to scroll back down to find my place again. 

Firefox Nightly on Android.

**Comment by roysix** [comment]
Hi again HowdHe. Thanks for opening this issue and for using Infy.

Under Infy's Options, in the `EXTRA` section, try unchecking the `Resize images and media that are bigger than the window (Recommended)` option.

This should hopefully keep Infy from trying to resize the `img` elements and append them as is, preventing the browser from jumping back up. Without Infy's resizing enabled though, you'll probably want to zoom out on your device so the newly appended images are fully visible; this may make the first image appear smaller than the other appended images (as it is now zoomed out).

Based on the Test URL I'm using, it seems like this issue is specific to Firefox Android when the images are bigger than the device size. The resize style changes Infy does are compatible with Desktop, but not Android, apparently.

Hope this helps!

**Comment by HowdHe** [comment]
I experimented a bit and here's what I found:

Turning off the resize option resulted in the scroll only loading the very next image in the sequence. Much larger,  and only a single image. The infinity loading loop would play indefinitely.

I was able to get it working WITH resizing turned on by going into the scroll section of the options and disabling update address bar and update tab.

At this point,  it works and loads all the images in a series, without automatically jumping back up.  However, if I scroll up even a single pixel while an image is loading, it does jump back to the top. But if I scroll down without scrolling up at all,  it won't jump back up.  

When I reach the end of a series,  and it's loading a bunch of broken image icons, it's common to have it jump back up at that point if I reverse direction and scroll back up while those are quickly loading.

**Comment by HowdHe** [comment]
A little further experimentation and I found that by changing the settings in Firefox nightly to not hide the toolbar when scrolling, the issue disappeared completely. Even with the update tabs and update address turned on, and image resizing turned on, it works perfectly, without jumping, even while loading the broken image icons at the end of the scroll. 

The issue, all along, has been that you cannot have the address toolbar automatically hide while scrolling.
