### ISSUE TITLE
保存的网址匹配规则

### ISSUE THREAD

**Issue by HarlockHomes** [roysix/infy-scroll#4]
关于保存的网址匹配规则，遇到的困难。
例如
对于一条规则需要生效的网址是，www.example.com/[any word]/，其中[any word]有许多无规律的字符。
另一条规则需要生效的网址是，www.example.com/[any word]/[any word]/，其中[any word]有许多无规律的字符。
如何只保存两条自动滚动规则 ，为了分别对大量网址起作用，而且不冲突。

**Comment by roysix** [comment]
Hi!

Thank you for opening this issue!

Can you try deleting the first URL you saved `www.example.com/[anyword]/` and start over by saving the URLs in this order?
1. `www.example.com/[anyword]/[anyword]/`
2. `www.example.com/[anyword]/`

This way, when you go to URL 2 (the less specific URL), it won't auto-activate using the URL 1 Pattern (the more specific URL) and will let you save both URL patterns. It currently thinks you are trying to override the first pattern, which perhaps isn't the best design choice.

If this helps, I would save them using the `Regular Expression` option using these patterns (in this order):
1. `www\.example\.com/.*/.*/`
2. `www\.example\.com/.*/`

I'll try and see if I can update the Save URL logic so that it doesn't replace the Saved URL patterns like it's doing right now and some other improvements.

Hope this helps a little bit!

**Comment by HarlockHomes** [comment]
非常感谢，问题解决了。
我依次建立的规则如下：
1 www\.example\.com/h.*
2 www\.example\.com/g.*
3 www\.example\.com/member
4 www\.example\.com/m.*
5 www\.example\.com/m.*/.*
它们工作的很好。

对于优先级、可编辑性，可恢复性，我觉得 uBlock Origin 的组成逻辑可以做为借鉴。

**Comment by HarlockHomes** [comment]
我遇到了一个特殊的情况，它是这样的在文章末尾， 
[pre article] : [article title]
[next article] : [article title]

[pre article] and [next article] 是固定的字符串，but it's not a link, the link is [article title]，
对于这种情况，应该怎样处理？

**Comment by sixcious** [comment]
Thank you for the reply/feedback and sorry for the inconvenience!

OK, in the Version 0.6 Update coming later this month, I'll try and change the way the URL matching works for `Pattern` mode to make it easier to save those type of URL patterns. This way you don't have use `Regular Expression` mode.

---

`[pre article] : [article title]`
`[next article] : [article title]`

If you can use your Browser's DevTools, you can right-click the `[article title]` link to try and generate a `Selector` or `XPath` rule for the `Next Link`.

But I think in this situation, the generated rule might fail on the next page if it uses `nth-child`. We might need to write a custom `Next Rule` (`Selector` or `XPath`) that looks for the link by using an element sibling or parent relationship with `[next article]`. I think I would need to see the website's HTML to be able to figure out the correct Selector or XPath rule.

Sorry I couldn't be more helpful, and thank you for using Infy.

**Comment by HarlockHomes** [comment]
太好了，按照操作步骤，成功了。
