### ISSUE TITLE
User Interface: Remember the last used mode

### ISSUE THREAD

**Issue by schittli** [roysix/infy-scroll#5]
Thanks a lot for this great and useful Tool!

### Describe the feature request you'd like
**Better default handling for the Scroll Mode (Next Link / Increment URL / ...) and Append Mode (Page / Iframe / Element / ...)**

Each time as I open Infy Scroll, I do the same thing:
1. Select: "Increment URL"
2. Select Append Mode: Element

#### Suggestion 1: UI remembers last used settings or the Options defines the default

It would be great if Infy Scroll:
- either remember the last used Infy Scroll Mode (Next Link / Increment URL / ...) and the last used Append Mode (Page / Iframe / Element / ...)
- or if one could define those default values in the Infy Scroll Options

#### Suggestion 2: Saved URLs knows which mode to use
It would be great if saved URLs automatically reuses the right Infy Scroll Mode (Next Link / Increment URL / ...) and the right Append Mode (Page / Iframe / Element / ...).
It would be useful if the Saved URLs saves those modes, too.

Thanks a lot, kind regards,
Thomas

**Comment by roysix** [comment]
Hi Thomas! Thank you for this feature request and for opening this issue.

**Re: Suggestion 1: UI remembers last used settings or the Options defines the default**
Are you able to get into Infy's Options by clicking the `GEAR` Icon in the lower-right corner? Infy currently uses the second approach you listed by letting you define those manually under options. So, under `Options` > `Scroll`, there's these two dropdowns for `Default Action` and `Default Append`. The one "gotcha" is that if Infy finds a Database URL (namely, one that matches a wide number of URLs like `^https?://.`), then it can't use the default settings, and instead defaults to using the Database URL settings, which is always `Next Link` and `Element`.

I'll try and see if I can implement it the first way you listed and have it simply remember the last used option if that's preferably; I tend to go back and forth on these type of implementation details.

![Issue 5-1](https://user-images.githubusercontent.com/1027814/105612695-92395400-5d8b-11eb-8a52-8b42f8f06d8a.png)

**Re: Suggestion 2: Saved URLs knows which mode to use**
Hmm... Unless there's a bug somewhere, Saved URLs should definitely be saving the Action and Append Mode (these are two of the most important settings they save). Are you clicking the `Heart Button`, followed by `YES` followed by `ACCEPT` and saving the URL with the correct pattern or regular expression? You can check by going under `Options` > `Saves` and by clicking the URL in the table to see the save's action and append mode to make sure everything looks right.

![Issue 5-2](https://user-images.githubusercontent.com/1027814/105612734-d298d200-5d8b-11eb-8ceb-0b855441a71e.png)

Hope this helps a little. Thank you for using Infy!

**Comment by zalewskigrzegorz** [comment]
I got this same problem. 
All changes that I made in the main window was wiped during page refresh:
https://user-images.githubusercontent.com/12560152/118400878-cfd82a80-b663-11eb-873b-bab29288db7f.mp4

Global addon options are persistent between reloads. Only rules disappear.

**Comment by roysix** [comment]
Hi @zalewskigrzegorz,

If you want Infy to remember the settings you made during a "page refresh" (in other words, visiting a site again), then you should `Save` the URL clicking the `Heart Button`, enter the correct pattern or regular expression, followed by `YES` followed by `ACCEPT` to finalize the save. This is especially true if you are trying to override a Database URL permanently.

If you want Infy to remember last used `Action` and `Append Mode` settings every time you click `ACCEPT`, then you can enable the new `Dynamic Settings` checkbox in the `Options` `UI` section. (Note that this setting doesn't apply when overriding Database URLs because those are almost always overridden on a situational basis.)

Hope that helps! I'm going to close this issue. If you are still having issues, feel free to [email me or open a new issue](https://github.com/roysix/infy-scroll/wiki/Help).
