### ISSUE TITLE
Add support for local files

### ISSUE THREAD

**Issue by Anangaya** [roysix/infy-scroll#8]
Awesome extension 👍 It would be even better if it can handle local url lists ( a list of url that begins like file:///)

**Comment by roysix** [comment]
Hi Anangaya,

Thanks so much for using Infy and for opening this issue!

This is technically possible to do, but you need to tell your browser it's OK. It's a complex security issue, primarily because browsers don't want JavaScript code to be able to load your other local files without your permission.

So, the way you tell your browser to disable the security constraint is:

- Chrome/Edge: Start Chrome/Edge from the command line with the [`--allow-file-access-from-files` flag](https://stackoverflow.com/a/18587027)
- Firefox: Navigate to `about:config` and search for and set `privacy.file_unique_origin` to `false`

(I obviously can't recommend leaving this setting on permanently!)

I'll try and add this info in the Help Guide.

Hope this helps!

**Comment by Anangaya** [comment]
Thanks. It works brilliantly! 

I didn't know about the security issue. I guess that's why most add-ons don't work with local file links but Copy All Urls for chrome did work with local files without any additional configurations though. Anyway I'm totally satisfied with infy now.
