### ISSUE TITLE
Breaks css markup

### ISSUE THREAD

**Issue by Dook1** [roysix/infy-scroll#82]
### Problem

The text no longer align to the left in attached content on the site - https://4pda.to/forum/index.php?showtopic=527737
The #cz2yYz0KMJXDFSdb {text-align: left} rule does not work for attached content because this content is no longer a child of #cz2yYz0KMJXDFSdb

### URL

https://4pda.to/forum/index.php?showtopic=527737

### Version

0.8

### Browser

FF 121

### OS

Win11

### Device

PC

### Adherence

- [X] I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/50) and my issue is directly related with the app and is not related to making it work with a specific website

**Comment by sixcious** [comment]
Hi Dook1!

This isn't really a bug or something I can fix, but here's two ways to make it do what you want:
1. Use the regular `Iframe` or `Element Iframe (Trim)` append modes to isolate each appended page's environment so that the CSS will work as is, without modification. Note that for the latter, you may have to adjust the `Page Element Path` to be one level higher than normal.
2. [Add a custom stylesheet or script](https://github.com/sixcious/infy-scroll/wiki/Scripts-and-Styles#custom-styles) using another extension like Stylus or ViolentMonkey and add a new CSS rule to left-align the content.

I hope this helps! 💜
